### ISSUE TITLE
Feld "data" optional für Success/Fail?

### ISSUE THREAD

**Issue by Dgame** [demvsystems/jsend#1]
Das Feld "data" ist laut Spezifikation für Success & Fail required, kann aber null/empty sein. Es bietet sich daher ggf. aus Bequemlichkeitsgründen an, dieses Feld als optional einzustufen.

**Comment by alexmpunkt** [comment]
Muss dann nur immer im Response gesetzt werden

**Comment by Dgame** [comment]
Was meinst du?

**Comment by alexmpunkt** [comment]
Welche Stelle meinst du denn? Habe das so verstanden, dass es im Code optional ist.
An der Stelle wo wir dann das Repsonse-Objekt bauen müssen wir es dann aber immer setzen, ggfl dann mit null.
Aber denke das war ja sowieso klar :wink:

**Comment by Dgame** [comment]
Ich meinte beim encode und decode. Also tatsächlich im Json.

**Comment by alexmpunkt** [comment]
Da es dem Standard entsprechen soll lassen wir Data immer drin, auch wenn es null ist
