### ISSUE TITLE
ResponseFactory: Add successOrFail helper for boolean responses

### ISSUE THREAD

**Issue by spaceemotion** [demvsystems/jsend#6]
Quite often we find ourselves writing the following snippet of code whenever we want to return either a success or fail message based on a boolean:

```php
$response = new JSendResponse($success ? Status::success() : Status::fail(), null);
$response->respond();
```

**Proposal**
Add a new `successOrFail` method to the `ResponseFactory` class so it can be used as follows:

```php
ResponseFactory::successOrFail($success)->respond();
ResponseFactory::successOrFail(true)->respond();
ResponseFactory::successOrFail(false)->respond();
```

The expected output for the `data` key is in all cases `null`.

**Comment by Dgame** [comment]
Usually, I'm strictly against boolean parameters - simply because it reeks. Give me some time to think about an alternative. Of course you are free to suggest one by yourself.

**Comment by Dgame** [comment]
#8
